force-app/main/default/objects/Calendar_Event__c/Calendar_Event__c.object-meta.xml
<CustomObject>
    <label>Calendar Event</label>
    <nameField>
        <displayFormat>CE-{0000000}</displayFormat>
        <label>CalendarEvent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calendar Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar_Event__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>End time of the event</description>
    <label>End Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Calendar_Event__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Start time of the event</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Calendar_Event__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Just the event title</description>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EventsCalendarController.cls
public with sharing class EventsCalendarController {
    
    @AuraEnabled(cacheable = true)
    public static ResponseWrapper getCalendarEvents(Date startDate, Date endDate) {
        
        try{
            Datetime startDT = Datetime.newInstance(startDate, Time.newInstance(0, 0, 0, 0));
            Datetime endDT = Datetime.newInstance(endDate, Time.newInstance(23, 59, 59, 999));

            List<Calendar_Event__c> calendarEvents = [
                SELECT 
                Id,
                Title__c,
                Start_Time__c,
                End_Time__c,
                Type__c
                FROM Calendar_Event__c
                WHERE Start_Time__c >= :startDT
                AND End_Time__c <= : endDT
                ORDER BY Start_Time__c ASC
            ];
            return new ResponseWrapper(JSON.serialize(calendarEvents), null, false);
        } catch (Exception e) {
            return new ResponseWrapper(null, e.getMessage() + '\n' + e.getLineNumber(), true);
        }
    }
    
    @AuraEnabled
    public static ResponseWrapper getUserTimeZone(){
        try {
            return new ResponseWrapper(UserInfo.getTimeZone().getID(), null, false);
        } catch (Exception e) {
            return new ResponseWrapper(null, e.getMessage() + '\n' + e.getLineNumber(), true);
        }
    }

    public class ResponseWrapper {
        @AuraEnabled public string response {get;set;}
        @AuraEnabled public string errorMessage {get;set;}
        @AuraEnabled public Boolean isError {get;set;}

        public ResponseWrapper(
            string response,
            string errorMessage,
            Boolean isError) {
                this.response = response;
                this.errorMessage = errorMessage;
                this.isError = isError;
        }
    }
}